import { MatchingHistoryItem } from "@/hooks/useMatchingHistory";

export const DUMMY_MATCHING_HISTORY: MatchingHistoryItem[] = [
  {
    historyId: 1,
    partner: {
      memberId: 1,
      email: "user1@test.com",
      nickname: "봄날의햇살",
      gender: "FEMALE",
      birthDate: "2002-03-15",
      mbti: "ENFP",
      intro: "안녕하세요! 맛집 탐방을 좋아하는 대학생입니다 😊",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "spring_sunshine_",
      university: "한국대학교",
      major: "경영학과",
      contactFrequency: "자주",
      hobbies: [
        { category: "CULTURE", name: "카페투어" },
        { category: "TRAVEL", name: "여행" },
        { category: "SPORTS", name: "필라테스" },
      ],
      tags: [{ tag: "친절함" }, { tag: "활발함" }],
      song: "IU - Love Wins All",
      intros: [
        { question: "제 키는", answer: "163cm" },
        { question: "제 음주 습관은", answer: "가끔" },
      ],
    },
    favorite: true,
    matchedAt: "2026-04-20T10:30:00.000000",
  },
  {
    historyId: 2,
    partner: {
      memberId: 2,
      email: "user2@test.com",
      nickname: "겨울바다",
      gender: "FEMALE",
      birthDate: "2001-11-22",
      mbti: "INFJ",
      intro: "조용하지만 깊은 대화를 좋아해요.",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "winter_sea22",
      university: "서울대학교",
      major: "심리학과",
      contactFrequency: "보통",
      hobbies: [
        { category: "CULTURE", name: "독서" },
        { category: "MUSIC", name: "피아노" },
      ],
      tags: [{ tag: "조용함" }, { tag: "진중함" }],
      song: "백예린 - 산책",
      intros: [
        { question: "제 직업은", answer: "대학원생" },
        { question: "제 키는", answer: "158cm" },
      ],
    },
    favorite: false,
    matchedAt: "2026-04-19T14:20:00.000000",
  },
  {
    historyId: 3,
    partner: {
      memberId: 3,
      email: "user3@test.com",
      nickname: "달빛소녀",
      gender: "FEMALE",
      birthDate: "2003-07-01",
      mbti: "ENTP",
      intro: "토론하는 거 좋아합니다! 같이 이야기해요~",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "KAKAO",
      socialAccountId: "moonlight_girl",
      university: "연세대학교",
      major: "컴퓨터공학과",
      contactFrequency: "자주",
      hobbies: [
        { category: "GAME", name: "보드게임" },
        { category: "DAILY", name: "코딩" },
        { category: "SPORTS", name: "배드민턴" },
        { category: "CULTURE", name: "영화감상" },
      ],
      tags: [{ tag: "재치있음" }, { tag: "논리적" }],
      song: "NewJeans - Ditto",
      intros: [
        { question: "제 직업은", answer: "개발자" },
        { question: "저는 흡연을", answer: "비흡연" },
      ],
    },
    favorite: true,
    matchedAt: "2026-04-18T09:15:00.000000",
  },
  {
    historyId: 4,
    partner: {
      memberId: 4,
      email: "user4@test.com",
      nickname: "여름향기",
      gender: "FEMALE",
      birthDate: "2000-08-10",
      mbti: "ISFP",
      intro: "그림 그리는 걸 좋아해요 🎨",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "summer_scent__",
      university: "고려대학교",
      major: "미술학과",
      contactFrequency: "적음",
      hobbies: [
        { category: "MUSIC", name: "그림" },
        { category: "TRAVEL", name: "사진촬영" },
      ],
      tags: [{ tag: "예술적" }, { tag: "차분함" }],
      song: "10CM - 그라데이션",
      intros: [
        { question: "제 키는", answer: "165cm" },
        { question: "제가 좋아하는 음식은", answer: "파스타" },
      ],
    },
    favorite: false,
    matchedAt: "2026-04-17T16:45:00.000000",
  },
  {
    historyId: 5,
    partner: {
      memberId: 5,
      email: "user5@test.com",
      nickname: "별빛나래",
      gender: "FEMALE",
      birthDate: "2002-01-28",
      mbti: "ESTJ",
      intro: "운동 좋아하고 활발한 성격이에요!",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "star_narae",
      university: "한양대학교",
      major: "체육학과",
      contactFrequency: "자주",
      hobbies: [
        { category: "SPORTS", name: "헬스" },
        { category: "SPORTS", name: "러닝" },
        { category: "DAILY", name: "요리" },
      ],
      tags: [{ tag: "에너지넘침" }, { tag: "건강함" }],
      song: "LE SSERAFIM - UNFORGIVEN",
      intros: [
        { question: "제 음주 습관은", answer: "즐기는 편" },
        { question: "제 키는", answer: "170cm" },
      ],
    },
    favorite: false,
    matchedAt: "2026-04-16T11:00:00.000000",
  },
  {
    historyId: 6,
    partner: {
      memberId: 6,
      email: "user6@test.com",
      nickname: "꽃잎사이로",
      gender: "FEMALE",
      birthDate: "2001-04-05",
      mbti: "INFP",
      intro: "감성적인 대화를 좋아해요 💐",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "flower_between",
      university: "이화여자대학교",
      major: "국문학과",
      contactFrequency: "보통",
      hobbies: [
        { category: "CULTURE", name: "시 쓰기" },
        { category: "CULTURE", name: "전시회" },
      ],
      tags: [{ tag: "섬세함" }, { tag: "감성적" }],
      song: "성시경 - 거리에서",
      intros: [
        { question: "제가 좋아하는 음식은", answer: "한식" },
        { question: "저는 흡연을", answer: "비흡연" },
      ],
    },
    favorite: true,
    matchedAt: "2026-04-15T08:30:00.000000",
  },
  {
    historyId: 7,
    partner: {
      memberId: 7,
      email: "user7@test.com",
      nickname: "하늘구름",
      gender: "FEMALE",
      birthDate: "2003-09-12",
      mbti: "ESFJ",
      intro: null,
      profileImageUrl: null,
      profileImageKey: null,
      socialType: null,
      socialAccountId: null,
      university: "성균관대학교",
      major: "의상학과",
      contactFrequency: "자주",
      hobbies: [
        { category: "DAILY", name: "쇼핑" },
        { category: "CULTURE", name: "뮤지컬" },
      ],
      tags: null,
      song: null,
      intros: [{ question: "제 키는", answer: "162cm" }],
    },
    favorite: false,
    matchedAt: "2026-04-14T13:20:00.000000",
  },
  {
    historyId: 8,
    partner: {
      memberId: 8,
      email: "user8@test.com",
      nickname: "파도소리",
      gender: "FEMALE",
      birthDate: "2000-12-25",
      mbti: "INTJ",
      intro: "효율적인 만남을 선호합니다.",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "wave_sound25",
      university: "KAIST",
      major: "전산학부",
      contactFrequency: "적음",
      hobbies: [
        { category: "GAME", name: "체스" },
        { category: "DAILY", name: "독서" },
        { category: "DAILY", name: "자기계발" },
      ],
      tags: [{ tag: "공부하는" }, { tag: "계획적" }],
      song: "Day6 - 한 페이지가 될 수 있게",
      intros: [
        { question: "제 직업은", answer: "연구원" },
        { question: "제 음주 습관은", answer: "전혀 안 함" },
      ],
    },
    favorite: false,
    matchedAt: "2026-04-13T17:50:00.000000",
  },
  {
    historyId: 9,
    partner: {
      memberId: 9,
      email: "withdrawn_9@deleted.com",
      nickname: "탈퇴한 사용자",
      gender: "FEMALE",
      birthDate: null,
      mbti: "ENFP",
      intro: null,
      profileImageUrl: null,
      profileImageKey: null,
      socialType: null,
      socialAccountId: null,
      university: "한국대학교",
      major: "(알 수 없음)",
      contactFrequency: "보통",
      hobbies: [{ category: "SPORTS", name: "헬스" }],
      tags: null,
      song: null,
      intros: [],
    },
    favorite: false,
    matchedAt: "2026-04-12T10:10:00.000000",
  },
  {
    historyId: 10,
    partner: {
      memberId: 10,
      email: "user10@test.com",
      nickname: "새벽이슬",
      gender: "FEMALE",
      birthDate: "2002-06-18",
      mbti: "ISTP",
      intro: "자전거 타고 한강 달리는 거 좋아해요 🚴",
      profileImageUrl: null,
      profileImageKey: null,
      socialType: "INSTAGRAM",
      socialAccountId: "dawn_dew_18",
      university: "중앙대학교",
      major: "기계공학과",
      contactFrequency: "보통",
      hobbies: [
        { category: "SPORTS", name: "자전거" },
        { category: "TRAVEL", name: "캠핑" },
        { category: "DAILY", name: "요리" },
      ],
      tags: [{ tag: "쿨함" }, { tag: "독립적" }],
      song: "ZICO - Any Song",
      intros: [
        { question: "제 키는", answer: "167cm" },
        { question: "제가 좋아하는 음식은", answer: "일식" },
        { question: "저는 흡연을", answer: "비흡연" },
      ],
    },
    favorite: true,
    matchedAt: "2026-04-11T19:00:00.000000",
  },
];
